filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /tmp/beacon0/*.json
    - /tmp/beacon2/*.json
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /tmp/beacon0/*.txt
    - /tmp/beacon1/*.txt
    - /tmp/beacon2/*.txt
    - /tmp/beacon3/*.txt

    - /tmp/shard0-0/*.txt
    - /tmp/shard0-1/*.txt
    - /tmp/shard0-2/*.txt
    - /tmp/shard0-3/*.txt

    - /tmp/shard1-0/*.txt
    - /tmp/shard1-1/*.txt
    - /tmp/shard1-2/*.txt
    - /tmp/shard1-3/*.txt

    - /tmp/shard2-0/*.txt
    - /tmp/shard2-1/*.txt
    - /tmp/shard2-2/*.txt
    - /tmp/shard2-3/*.txt

    - /tmp/shard3-0/*.txt
    - /tmp/shard3-1/*.txt
    - /tmp/shard3-2/*.txt
    - /tmp/shard3-3/*.txt

    - /tmp/shard4-0/*.txt
    - /tmp/shard4-1/*.txt
    - /tmp/shard4-2/*.txt
    - /tmp/shard4-3/*.txt

    - /tmp/shard5-0/*.txt
    - /tmp/shard5-1/*.txt
    - /tmp/shard5-2/*.txt
    - /tmp/shard5-3/*.txt

    - /tmp/shard6-0/*.txt
    - /tmp/shard6-1/*.txt
    - /tmp/shard6-2/*.txt
    - /tmp/shard6-3/*.txt

    - /tmp/shard7-0/*.txt
    - /tmp/shard7-1/*.txt
    - /tmp/shard7-2/*.txt
    - /tmp/shard7-3/*.txt

# output.logstash:
#   hosts: ["127.0.0.1:5000"]
#   username: "elastic",
#   password: "changeme"

output.logstash:
  hosts: ["34.94.185.164:5000"]

