name: "testnet-2"
genesis_param: 
  initial_incognito: 
    - Version: 1
      Type: "s"
      LockTime: 1570159128
      SigPubKey: "5xVSzcZpA3uHmBO5ejENk13iayexILopySACdieLugA="
      Fee: 0
      Sig: "oMJPBLxKgTnfQhMgfvvH68ed0UTuTfl3ofOoWgk8dgvfhovgvued9HH4dXz60rY32H4Y4c85Zd8bSXSnvNhZAA=="
      Proof: "AAAAAAAAAbAAriDnFVLNxmkDe4eYE7l6MQ2TXeJrJ7EguinJIAJ2J4u6ACARCc1/qyLEePe1zSthzmRSqf2VNOlo036JwtDgbNg24yAb6hGuk1tRBVMO4ruHaNEasY09ZiBc4iuK/dpDSyNTCCABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDMoX8yNBbY68SO44umD1CMfz/r0T4YiXhDgDgT6+k4BgdY0V4XYoAAAAAAAAAAAAA="
      PubKeyLastByteSender: 0
  fee_per_tx_kb: 0
  consensus_algorithm: "bls"
  block_timestamp: "2020-08-11T00:00:00.000Z"
  tx_stake: "d0e731f55fa6c49f602807a6686a7ac769de4e04882bb5eaf8f4fe209f46535d"
  
committee_size:
  max_shard_committee_size: 32
  min_shard_committee_size: 4
  min_beacon_committee_size: 4
  max_beacon_committee_size: 4
  init_shard_committee_size: 4
  init_beacon_committee_size: 4
  shard_committee_size_key_list_v2: 4
  beacon_committee_size_key_list_v2: 4
  number_of_fixed_shard_block_validators: 4
block_time:
  min_shard_block_interval: 10000000000
  max_shard_block_creation: 8000000000
  min_beacon_block_interval: 10000000000
  max_beacon_block_creation: 6000000000
staking_amount_shard: 1750000000000
active_shards: 8
basic_reward: 400000000
epoch_param:
  number_of_block_in_epoch: 100
  number_of_block_in_epoch_v2: 1000000000000
  epoch_v2_break_point: 1000000000000
  random_time: 50
  random_time_v2: 1000000000000
eth_contract_address: "0x2f6F03F1b43Eab22f7952bd617A24AB46E970dF7"
dao_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci" # community fund
centralized_website_payment_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci"
swap_committee_param:
  offset: 1
  swap_offset: 1
  assign_offset: 2
consensus_param: 
  consensus_v2_epoch: 1
  staking_flow_v2_height: 2051863
  enable_slashing_height: 2087789
  timeslot: 10
  epoch_break_point_swap_new_key: # read from file key list v2 
    - 1000000000
beacon_height_break_point_burn_addr: 1
eth_remove_bridge_sig_epoch: 2085
replace_staking_tx_height: 1
bc_height_break_point_new_zkp: 1148608
enable_feature_flags:
  - 0: 1
  - 1: 0
portal_param:
  bc_height_break_point_portal_v3: 1328816
  portal_param_v3:
    0: 
      time_out_custodian_return_pub_token: 15m
      time_out_waiting_porting_request: 15m
      time_out_waiting_redeem_request: 10m
      max_percent_liquidated_collateral_amount: 105
      max_percent_custodian_rewards: 10
      min_percent_custodian_rewards: 1
      min_lock_collateral_amount_in_epoch: 10000
      min_percent_locked_collateral: 150
      tp120: 120
      tp130: 130
      min_percent_porting_fee: 0.01
      min_percent_redeem_fee: 0.01
      supported_collateral_tokens: 
        - external_token_id: "0000000000000000000000000000000000000000"
          decimal: 9
        - external_token_id: "3a829f4b97660d970428cd370c4e41cbad62092b"
          decimal: 6
        - external_token_id: "75b0622cec14130172eae9cf166b92e5c112faff"
          decimal: 6
      min_portal_fee: 100
      portal_tokens: 
        ef5947f70ead81a76a53c7c8b7317dd5245510c665d3a13921dc9a581188728b:
          chain_id: "Bitcoin-Testnet"
        6abd698ea7ddd1f98b1ecaaddab5db0453b8363ff092f0d8d7d4c6b1155fb693:
          chain_id: "Binance-Chain-Ganges"
      portal_feeder_address: "12S2ciPBja9XCnEVEcsPvmCLeQH44vF8DMwSqgkH7wFETem5FiqiEpFfimETcNqDkARfht1Zpph9u5eQkjEnWsmZ5GB5vhc928EoNYH"
      portal_eth_contract_address: "0xF7befD2806afD96D3aF76471cbCa1cD874AA1F46"
      min_unlock_over_rate_collaterals: 25
  relaying_param:
    bnb_relaying_header_chain_id: "Binance-Chain-Ganges"
    btc_relaying_header_chain_id: "Bitcoin-Testnet-2"
    btc_data_folder_name: "btcrelayingv11"
    bnb_full_node_protocol: "https"
    bnb_full_node_host: "data-seed-pre-0-s3.binance.org"
    bnb_full_node_host: "443"
