name: "testnet-1"
net: 0x16
genesis_param:
  initial_incognito:
    - Version: 1
      Type: "s"
      LockTime: 1570159128
      SigPubKey: "5xVSzcZpA3uHmBO5ejENk13iayexILopySACdieLugA="
      Fee: 0
      Sig: "oMJPBLxKgTnfQhMgfvvH68ed0UTuTfl3ofOoWgk8dgvfhovgvued9HH4dXz60rY32H4Y4c85Zd8bSXSnvNhZAA=="
      Proof: "AAAAAAAAAbAAriDnFVLNxmkDe4eYE7l6MQ2TXeJrJ7EguinJIAJ2J4u6ACARCc1/qyLEePe1zSthzmRSqf2VNOlo036JwtDgbNg24yAb6hGuk1tRBVMO4ruHaNEasY09ZiBc4iuK/dpDSyNTCCABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDMoX8yNBbY68SO44umD1CMfz/r0T4YiXhDgDgT6+k4BgdY0V4XYoAAAAAAAAAAAAA="
      PubKeyLastByteSender: 0
  fee_per_tx_kb: 0
  consensus_algorithm: "bls"
  block_timestamp: "2020-08-11T00:00:00.000Z"
  tx_stake: "d0e731f55fa6c49f602807a6686a7ac769de4e04882bb5eaf8f4fe209f46535d"

committee_size:
  max_shard_committee_size: 32
  min_shard_committee_size: 4
  min_beacon_committee_size: 4
  max_beacon_committee_size: 4
  init_shard_committee_size: 4
  init_beacon_committee_size: 4
  shard_committee_size_key_list_v2: 4
  beacon_committee_size_key_list_v2: 4
  number_of_fixed_shard_block_validators: 4
  increase_max_shard_committee_size:
    - 1000000000000: 48
block_time:
  min_beacon_block_interval: 10s
  max_beacon_block_creation: 8s
  min_shard_block_interval: 10s
  max_shard_block_creation: 6s
staking_amount_shard: 1750000000000
active_shards: 8
basic_reward: 400000000
epoch_param:
  number_of_block_in_epoch: 100
  number_of_block_in_epoch_v2: 1000000000000
  epoch_v2_break_point: 1000000000000
  random_time: 50
  random_time_v2: 1000000000000
eth_contract_address: "0xE0D5e7217c6C4bc475404b26d763fAD3F14D2b86"
bsc_contract_address: "0x1ce57B254DC2DBB41e1aeA296Dc7dBD6fb549241"
prv_erc20_contract_address: "0x917637E3E1ee531231747690189e22C5FA38D88C"
prv_bep20_contract_address: "0x3d2E0c1b0b2d81D1A76544E6cC08670af9b86531"
dao_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci" # community fund
centralized_website_payment_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci"
swap_committee_param:
  offset: 1
  swap_offset: 1
  assign_offset: 2
consensus_param:
  consensus_v2_epoch: 15290
  staking_flow_v2_height: 2051863
  enable_slashing_height: 2087789
  assign_rule_v3_height: 2823522
  enable_slashing_height_v2: 2823650
  staking_flow_v3_height: 2823780
  lemma2_height: 2884002
  force_not_use_burned_coins: 1000000000000
  block_producing_v3_height: 1000000000000
  byzantine_detector_height: 2886522
  timeslot: 10
  epoch_break_point_swap_new_key: # read from file key list v2
    - 1280
beacon_height_break_point_burn_addr: 1
eth_remove_bridge_sig_epoch: 2085
replace_staking_tx_height: 1
bc_height_break_point_new_zkp: 1148608
bc_height_break_point_privacy_v2: 2823446
coin_v2_lowest_height: 2400000
enable_feature_flags:
  - PortalRelaying: 1
  - PortalV3: 0
  - PortalV4: 1
portal_v3_height: 1328816
tx_pool_version: 0
geth_param:
  host: "kovan.infura.io/v3/1138a1e99b154b10bae5c382ad894361"
  protocol: "https"
  port: ""
bsc_param:
  host: "https://data-seed-prebsc-2-s3.binance.org:8545"
is_enable_bpv3_stats: false
